from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess
from typing import Any

from app.solver_framework.registry import registry


def _ui_descriptor(value: Any) -> Any:
    if isinstance(value, list):
        return [_ui_descriptor(item) for item in value]
    if isinstance(value, dict):
        return {
            key: _ui_descriptor(item)
            for key, item in value.items()
            if key != "tensorOrder"
        }
    return value


def _catalog_source() -> str:
    sections = [
        "// Generated by python -m app.solver_framework.codegen. Do not edit.",
        "import { defineKernelTask } from '../authoring'",
        "import type { KernelDescriptor, KernelTaskConfig } from '../kernelContract'",
        "",
    ]
    catalog_entries = []
    for manifest in registry.manifests():
        authoring_name = manifest["authoringName"]
        descriptor_name = f"{authoring_name}Descriptor"
        descriptor_json = json.dumps(
            _ui_descriptor(manifest["descriptor"]),
            ensure_ascii=False,
            indent=2,
        )
        sections.extend(
            [
                f"export const {descriptor_name} = Object.freeze({descriptor_json}) as unknown as KernelDescriptor",
                "",
                f"export const {authoring_name}KernelRef = Object.freeze({{",
                f"  name: {descriptor_name}.name,",
                f"  version: {descriptor_name}.version,",
                "})",
                "",
                f"export function {authoring_name}(config: KernelTaskConfig) {{",
                f"  return defineKernelTask({descriptor_name}, config)",
                "}",
                "",
            ]
        )
        catalog_entries.append(
            "\n".join(
                [
                    "  Object.freeze({",
                    f"    authoringName: {json.dumps(authoring_name)},",
                    f"    builder: {authoring_name},",
                    f"    descriptor: {descriptor_name},",
                    "  }),",
                ]
            )
        )
    sections.extend(
        [
            "const productionKernelCatalog = Object.freeze([",
            *catalog_entries,
            "])",
            "",
            "export const kernelModules = Object.freeze(",
            "  productionKernelCatalog.map(({ descriptor }) => Object.freeze({ descriptor })),",
            ")",
            "",
            "export const kernelAuthoring = Object.freeze(",
            "  Object.fromEntries(productionKernelCatalog.map(({ authoringName, builder }) => [authoringName, builder])),",
            ")",
            "",
        ]
    )
    return "\n".join(sections)


def _format_source(ui_root: Path, destination: Path, source: str) -> str:
    prettier = ui_root / "node_modules" / "prettier" / "bin" / "prettier.cjs"
    if not prettier.is_file():
        raise SystemExit(f"Caemble UI dependencies are not installed; missing {prettier}")
    process = subprocess.run(
        ["node", str(prettier), "--stdin-filepath", str(destination)],
        input=source,
        capture_output=True,
        cwd=ui_root,
        encoding="utf-8",
        check=False,
    )
    if process.returncode != 0:
        raise SystemExit(process.stderr.strip() or "Prettier failed to format the generated catalog")
    return process.stdout


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate the Caemble kernel catalog from CAE solver manifests.")
    parser.add_argument("--caemble-ui", required=True, type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    destination = (
        args.caemble_ui.resolve()
        / "src"
        / "lib"
        / "cad"
        / "simulation"
        / "kernels"
        / "generated.ts"
    )
    if not (args.caemble_ui / "package.json").is_file():
        parser.error(f"--caemble-ui must point to the Caemble UI package: {args.caemble_ui}")
    expected = _format_source(args.caemble_ui.resolve(), destination, _catalog_source())
    actual = destination.read_text(encoding="utf-8") if destination.is_file() else None
    if args.check:
        if actual != expected:
            raise SystemExit(f"Generated Caemble kernel catalog is stale: {destination}")
        return
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(expected, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
